services:
#    application_locale.example:
#        class: Application\LocaleBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    application_locale_service:
        class:      Application\LocaleBundle\Services\LocaleService
        arguments:  [@service_container, @router]

    application_locale_extension:
        class:      Application\LocaleBundle\Extension\LocaleExtension
        arguments:  [@service_container]
        tags:
            - { name: 'twig.extension'}