application_backend_group_index:
    pattern:  /
    defaults: { _controller: "ApplicationBackendBundle:Group:index" }

application_backend_group_add:
    pattern: /add
    defaults: { _controller: "ApplicationBackendBundle:Group:add" }

application_backend_group_edit:
    pattern: /{groupID}/edit
    defaults: { _controller: "ApplicationBackendBundle:Group:edit" }

application_backend_group_delete:
    pattern: /{groupID}/delete
    defaults: { _controller: "ApplicationBackendBundle:Group:delete" }

application_backend_group_add_user:
    pattern: /{groupID}/add
    defaults: { _controller: "ApplicationBackendBundle:Group:addUser" }

application_backend_group_show_user:
    pattern: /{groupID}/show
    defaults: { _controller: "ApplicationBackendBundle:Group:showUser" }

application_backend_group_delete_user:
    pattern: /{groupUserID}/delete-user
    defaults: { _controller: "ApplicationBackendBundle:Group:deleteUser" }