application_backend_index:
    pattern:   /
    defaults: { _controller: "ApplicationBackendBundle:Default:index" }

application_backend_product:
    resource: "@ApplicationBackendBundle/Resources/config/routes/product.yml"
    prefix: /product

application_backend_cms_page:
    resource: "@ApplicationBackendBundle/Resources/config/routes/cms-page.yml"
    prefix:   /cms-page

application_backend_user:
    resource: "@ApplicationBackendBundle/Resources/config/routes/user.yml"
    prefix:   /user

application_backend_group:
    resource: "@ApplicationBackendBundle/Resources/config/routes/group.yml"
    prefix:   /department

application_backend_task:
    resource: "@ApplicationBackendBundle/Resources/config/routes/task.yml"
    prefix:   /task

application_backend_log:
    resource: "@ApplicationBackendBundle/Resources/config/routes/log.yml"
    prefix:   /log

application_backend_report:
    resource: "@ApplicationBackendBundle/Resources/config/routes/report.yml"
    prefix:   /report