application_frontend_homepage:
    path:     /
    defaults: { _controller: ApplicationFrontendBundle:Task:index }

application_frontend_task:
    resource: "@ApplicationFrontendBundle/Resources/config/routes/task.yml"
    prefix: /task

application_frontend_user:
    resource: "@ApplicationFrontendBundle/Resources/config/routes/user.yml"
    prefix: /user

application_frontend_errorpage:
    path:     /error
    defaults: { _controller: ApplicationFrontendBundle:Default:error }

application_frontend_login:
    pattern:   /login
    defaults: { _controller: "ApplicationBackendBundle:Security:login" }

application_frontend_login_check:
    pattern:   /check-login
    defaults: { _controller: "FOSUserBundle:Security:check" }

application_frontend_logout:
    pattern:   /logout