services:
#    application_frontend.example:
#        class: Application\FrontendBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    application.frontend.exception_controller:
        parent: twig.controller.exception
        class: Application\FrontendBundle\Controller\ExceptionController