<?php

namespace Application\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
	/**
	 * Filter user with filter/paging
	 * @author Alex
	 * @param array $aFilters
	 * @param integer $limit
	 * @param integer $offset
	 */
	public function filter($limit, $offset, $aFilters) {
		$qb = $this->createQueryBuilder('u');
		$qb->where('u.locked = 0');
		$qb->setFirstResult($offset);
		if (0 <= $limit) {
			$qb->setMaxResults($limit);
		}
		if (isset($aFilters['id'])) {
			$qb->orderBy('u.id', $aFilters['id']);
		}
		if (isset($aFilters['username'])) {
			$qb->orderBy('u.username', $aFilters['username']);
		}
		if (isset($aFilters['last_login'])) {
			$qb->orderBy('u.last_login', $aFilters['last_login']);
		}
		if (isset($aFilters['created_date'])) {
			$qb->orderBy('u.created_date', $aFilters['created_date']);
		}
		if (isset($aFilters['updated_date'])) {
			$qb->orderBy('u.updated_date', $aFilters['updated_date']);
		}

		$results = $qb->getQuery()->getResult();
		return $results;
	}

	/**
	 * Count all
	 * @author Alex
	 * Return count
	 */
	public function count() {
		$qb = $this->createQueryBuilder('u');
		$qb->where('u.locked = 0');
		$qb->select($qb->expr()->countDistinct('u.id'));
		$count = $qb->getQuery()->getSingleScalarResult();
		return $count;
	}

	/**
	 * Count by username
	 * @author Alex
	 * Return count
	 */
	public function countByUsername($username) {
		$qb = $this->createQueryBuilder('u');
		$qb->where('u.username = :username');
		$qb->setParameter('username', $username);
		$qb->select($qb->expr()->countDistinct('u.id'));
		$count = $qb->getQuery()->getSingleScalarResult();
		return $count;
	}
}
